# used for verifying signed cookies
# restart server on modification

# generate secure secret key:
# $ rails secret

development:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

test:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
